#!/usr/bin/env bash

# install -- make symbolic links in the users home directory
# Mike Barker <mike@thebarkers.com>
# May 14th, 2013

# 2016.10.01 MRB
# Modified to install tmux config file

# list of files and or directories to install
file_list=".tmux.conf .tmux-darwin.conf"

# Get the current working directory
cwd="$(cd "$(dirname "$0")" && pwd)"

# Backup a file if it exists
backup() {
	local file=$1
	if [[ -e ${file} ]]; then
		if [[ ! -h ${file} ]]; then
			echo "Backing up file ${file}"
			mv -v ${file} ${file}.backup
		fi
	fi
}

# Create a symbolic link file that points to the source file.
link() {
    local src=$1
    local dst=$2
    local ln_flags=-sv
    if [[ -h ${dst} ]]; then
        if [[ $(readlink ${dst}) == ${src} ]]; then
            return
        fi
        ln_flags=-sfnv
    fi
    if [[ ! -e ${dst} ]]; then
        echo "Linking file ${dst}"
        ln ${ln_flags} ${src} ${dst}
    fi
}

# install the files and or directories
for file in ${file_list}
do
    backup "${HOME}/${file}"
    link "${cwd}/${file}" "${HOME}/${file}"
done
