#!/usr/bin/env bash

# install -- make symbolic links in the users home directory
# Mike Barker <mike@thebarkers.com>
# May 14th, 2013

# 2023.07.23 MRB
# - Clone the Tmux Plugin Manager (tpm) into the tmux-plugins folder
# 2019.04.22 MRB
# - Misc cleanup
# 2017.10.04 MRB
# - Generalized install script, installs everthing under the 'home' folder into
# the users $HOME folder.
# 2016.10.01 MRB
# Modified to install tmux config file

# Backup a file/directory by renaming it with the current date and time
backup_file() {
	file=$1
	file_ext=$(date +%Y%m%d%H%M)

	if [ -e "${file}" ]; then
		if ! [ -h "${file}" ]; then
			echo "Backing up ${file} to: ${file}.${file_ext}"
			mv "${file}" "${file}.${file_ext}"
		fi
	fi
}

# create a symbolic link if one does not allready exist
link_file() {
    local src=$1
    local dst=$2

    if ! [ -e "${dst}" ]; then
        echo "Linking file ${dst}"
        ln -sfnv "${src}" "${dst}"
    fi
}

# Backup existing files and link files/dirs in the home folder into
# the users home directory.
DIR="$(cd "$(dirname "$0")" && pwd)"
shopt -s dotglob
for src in "${DIR}"/home/*; do
    dst="${HOME}"/$(basename "$src")
    backup_file "$dst"
    link_file "$src" "$dst"
done
shopt -u dotglob

# Clone the Tmux Plugin Manager
dst="${HOME}/.tmux/plugins/tpm"
if [[ ! -d  "${dst}" ]]; then
    git clone https://github.com/tmux-plugins/tpm "${dst}"
fi
